## Example: ##
# wood:                    # The name of the item. Used in commands, ex. /buy wood 64
#     value: -0.65         # The current value of wood. (don't worry if this is negative)
#     number: 17           # The 'regular' data value of wood
#     minValue: 0.01       # The minimum amount you want one wood to sell/buy for
#     maxValue: 10000.0    # The maximum amount you want one wood to sell/buy for
#     changeRate: 0.01     # The amount you want added/subtracted to wood's value when bought/sold
#     data: '0'            # The 'second' data value. 0 is the byte data for regular wood
#     spread: 0.01         # The transaction fee for selling. Keep this equal to changeRate for
#                          #     normal use. Set it larger than changeRate for a 'money sink'
#                          #     Don't set it less than changeRate unless you know what you're doing
wood:
     value: -0.65
     number: 17
     minValue: 0.01
     maxValue: 10000.0
     changeRate: 0.01
     data: '0'
     spread: 0.01
ink:
    value: 9.08
    number: 351
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
lapis:
    value: 0.02
    number: 351
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '4'
    spread: 0.01
cocoa:
    value: 10.1
    number: 351
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '3'
    spread: 0.01
spruce:
    value: -4.3
    number: 17
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '1'
    spread: 0.01
birch:
    value: -4.93
    number: 17
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '2'
    spread: 0.01
fish:
    value: 9.83
    number: 349
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
beef:
    value: 8.01
    number: 363
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
stone:
    value: -1.92
    number: 1
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
egg:
    value: 9.96
    number: 344
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
feather:
    value: 14.62
    number: 288
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
soulsand:
    value: 9.65
    number: 88
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
rottenflesh:
    value: 8.63
    number: 367
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
slime:
    value: 12.82
    number: 341
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
obsidian:
    value: 12.34
    number: 49
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
flint:
    value: 9.23
    number: 318
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
snow:
    value: 0.02
    number: 332
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
brownmushroom:
    value: 6.24
    number: 39
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
dirt:
    value: -50.11
    number: 3
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
wool:
    value: 9.63
    number: 35
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
leather:
    value: 9.3
    number: 334
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
cobblestone:
    value: -20.82
    number: 4
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
mossstone:
    value: 9.96
    number: 48
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
grass:
    value: 9.96
    number: 31
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
vine:
    value: 8.51
    number: 106
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
rose:
    value: 9.73
    number: 38
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
apple:
    value: 10.01
    number: 260
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
pork:
    value: 9.91
    number: 319
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
pumpkin:
    value: 9.57
    number: 86
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
pumpkinseeds:
    value: 10.1
    number: 361
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
clay:
    value: -1.34
    number: 337
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
gunpowder:
    value: 14.11
    number: 289
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
sandstone:
    value: 0.87
    number: 24
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
melonseeds:
    value: 9.73
    number: 362
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
melon:
    value: 0.26
    number: 360
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
gravel:
    value: -2.89
    number: 13
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
sugarcane:
    value: 0.02
    number: 338
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
iron:
    value: 12.22
    number: 265
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
chicken:
    value: 9.89
    number: 365
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
coal:
    value: -0.03
    number: 263
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
glowstone:
    value: 16.82
    number: 348
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
diamond:
    value: 21.75
    number: 264
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
bone:
    value: 9.48
    number: 352
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
netherrack:
    value: -6.42
    number: 87
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
seeds:
    value: -5.24
    number: 295
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
gold:
    value: 14.76
    number: 266
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
sand:
    value: -0.11
    number: 12
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
sapling:
    value: -3.23
    number: 6
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
sprucesapling:
    value: -2.86
    number: 6
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '1'
    spread: 0.01
birchsapling:
    value: -3.0
    number: 6
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '2'
    spread: 0.01
dandelion:
    value: 8.64
    number: 37
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
redmushroom:
    value: 8.69
    number: 40
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
enderpearl:
    value: 9.93
    number: 368
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
string:
    value: 6.15
    number: 287
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
redstone:
    value: 0.02
    number: 331
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
cactus:
    value: 4.76
    number: 81
    minValue: 0.01
    maxValue: 10000.0
    changeRate: 0.01
    data: '0'
    spread: 0.01
